# Adding elements in array.

In [2]:
import numpy as np

In [3]:
a = np.arange(0, 11, 2)
print(a)

[ 0  2  4  6  8 10]


In [4]:
#Now let us insert number 12 after second element in array.

In [8]:
a = np.insert(a, 2, 12)
print(a)


[ 0  2 12  4  6  8 10]


In [ ]:
#Instead of insert you can also use append function to add the element in the array. But
#remember that append can add element at the end only.

In [9]:
a = np.arange(0, 11, 2)
print(a)

[ 0  2  4  6  8 10]


In [11]:
a = np.append(a, 12)
print(a)

[ 0  2  4  6  8 10 12]


# Deleting elements in array.

In [12]:
a = np.arange(0, 11, 2)
print(a)

[ 0  2  4  6  8 10]


In [13]:
a = np.delete(a, 2)
print(a)


[ 0  2  6  8 10]


# Indexing and Slicing

In [15]:
data = np.array([1, 2, 3])
data[0]
data[1]
data[0:2]
data[1:]
data[-2:]
data

array([1, 2, 3])

In [ ]:
#1. Arithmetic operations

In [19]:
data = np.array([1,2])
ones = np.ones(2, dtype=int)
print(data+ones)


[2 3]


In [ ]:
#example on 2-dimension array

In [24]:
x = np.array([[1, 1], [2, 1]])
y = np.array([[2, 2], [3, 4]])
print(x * y) # elementwise product
print(x @ y) # matrix product
print(x + y)
print(x)

[[2 2]
 [6 4]]
[[5 6]
 [7 8]]
[[3 3]
 [5 5]]
[[1 1]
 [2 1]]


In [ ]:
#2. Functions 

In [25]:
x = np.array([1, 2, 3, 4])
print(x.sum())
print(x.max())
print(x.min())

10
4
1


In [ ]:
#example on 2-dimension array

In [26]:
y = np.array([[1, 1], [2, 2]])
print(y.sum(axis=0))
print(y.sum(axis=1))

[3 3]
[2 4]


In [27]:
data = np.array([[1, 2], [5, 3], [4, 6]])
print (data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 5 6]


In [ ]:
#Some more functions

In [28]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
print(np.unique(a))
print(np.flip(a)) # to reverse the array

[11 12 13 14 15 16 17 18 19 20]
[20 19 18 14 11 13 12 17 16 15 14 13 12 11 11]


In [29]:
x = np.array([[1, 2], [3, 4], [5, 6]])
print(x)
print(x.transpose())

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [30]:
x1 = np.array([[1, 2], [3, 4]])
x2 = np.array([[5, 6], [7, 8]])
print(np.vstack((x1, x2))
print(np.hstack((x1, x2))

SyntaxError: '(' was never closed (963423398.py, line 4)

In [31]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(x.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [3]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(x.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# Array Input and Output

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])
np.save('f1', a)
b = np.load('f1.npy')
print(b)


[1 2 3 4 5 6]
