In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3,4,5,6,7,8])  # One dimensional array
a1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
a2 = np.array([[1,2],[3,4]])   # Two dimensional array
a2

array([[1, 2],
       [3, 4]])

In [5]:
a3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])   #Three dimensional array
a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

# shape 
## Returns current shape of the array

In [6]:
print(a1.shape, a2.shape, a3.shape)

(8,) (2, 2) (2, 2, 2)


In [7]:
a3.shape

(2, 2, 2)

In [8]:
a2.shape

(2, 2)

In [9]:
a1.shape

(8,)

# size 
## It Returns the Total Number of Elements in the Array

In [10]:
print(a1.size, a2.size, a3.size)

8 4 8


# itemsize
## Returns the length of one element in bytes

In [11]:
a1.itemsize

4

# dtype

In [12]:
a1.dtype

dtype('int32')

# Transpose

In [13]:
a1.T

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
a2

array([[1, 2],
       [3, 4]])

In [16]:
a2.T

array([[1, 3],
       [2, 4]])

In [17]:
a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
a3.T

array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])

# ndim
## Returns total number of dimentions

In [19]:
print(a1.ndim, a2.ndim, a3.ndim)

1 2 3
